### PR TITLE
Resume snapshot instead of attempting to boot it (which fails)

### PR DESCRIPTION
**Pull request by tklengyel**

### CODE REVIEW

**Comment by tklengyel** [comment]
Thanks for creating the plugin by the way! ;)

**Comment by kill-9-me** [comment]
Interesting. SnapShots I take cannot be resumed but only booted (limitations of the free license i guess). I may instead add a configuration option to tell Cuckoo if it was a live snapshot.

**Comment by kill-9-me** [comment]
Actually, I'm going to take it one step further and have the system automatically figure out if the snapshot is resumable or bootable using the XenAPI.

**Comment by tklengyel** [comment]
Sounds good! I had this issue on free license xenserver 6.2 btw.

**Comment by tklengyel** [comment]
@kill-9-me: Ah, you know why I had this issue? I created full VM snapshots (including memory). You probably had basic (LVM only) snapshots..

**Comment by ghost** [comment]
Hey! Any luck on getting the VM's to boot from a snapshot? I'm running XenServer 6.0. If not, ill see if i can get the code to do this. Getting this working with XenServer over virtualbox is awesome.

**Comment by tklengyel** [comment]
@alphaseclabs: yes, I'm using the version in this PR and it works just fine.

**Comment by ghost** [comment]
@tklengyel, thanks for the reply. How are you taking the snapshots for the VM's?  I've been doing mine through XenConsole. Also, are you using xenserver 6.2 or 6.0 free license?

**Comment by tklengyel** [comment]
@alphaseclabs: I'm using the latest XenServer (6.2). The snapshots were taken using XenClient with the combined disk/memory snapshot function!

**Comment by kill-9-me** [comment]
Sorry I haven't looked at this recently. Life has been getting in my way. 

My plan is still to get the status of the VMs and resume or start them as applicable.

**Pull request closed without merging**
